### ISSUE TITLE
(redundant) Mount directories by auto-detecting their ipfs-pack manifests or prebuilt object databases

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#110]
Replaced by #95

# Stories

- [ ]  #108 Mount a directory based on its ipfs-pack manifest
- [ ] #109 Mount a directory based on its prebuilt ipfs-pack object database
- [ ] #111 Auto-detect ipfs-pack manifests and/or object databases
