### ISSUE TITLE
IPFS Pack Works With Content That Changes Over Time

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#132]
In order for ipfs-pack to work with content that changes over time, we need to implement:
- [ ] #109 Serve Content from Local Packs Through a Main IPFS node
- [ ] #93 Update, Rename or Delete Contents of an IPFS Pack
- [ ] #94 Tracked content is not available
