### ISSUE TITLE
Sprint: Data.Gov (aka 300 TB Challenge)

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#87]
**Dates**: 16-27 January 2017
**Sprint Milestone**: https://github.com/ipfs/archives/milestone/1
**PM**: @flyingzumwalt

# Objective

Work with collaborating institutions to load 350 TB of datasets from data.gov into IPFS and allow participants around the world to replicate the datasets onto their IPFS nodes.

**Comment by flyingzumwalt** [comment]
@jbenet suggested [here](https://github.com/ipfs/pm/issues/309#issuecomment-272744211):
> Some things to do that would help, before tue:

> - review existing filestore stuff
> - review ipfs-pack draft proposal -- https://github.com/ipfs/notes/issues/205
> - make a short list of the "big bugs" and "big optimizations" relevant for this sprint. (i can think of a couple -- file attrs, bitswap supporting paths (kills so many RTTs)  -- , but we'll want a good list to have in mind) 
> - refine the concrete use case and UX we're shooting for
> - create the test workloads + scripts we'll work against:
>   - for each order of magnitude of total data, from 1M -> 100TB
>   - with giant files
>   - with lots of little files
>   - can just add tests to https://github.com/ipfs/fs-stress-test
> - review ipfs-s3 datastore options -- https://github.com/ipfs/notes/issues/214

**Comment by flyingzumwalt** [comment]
## Sprint Prep Action Items

### @jbenet:
- [ ] #99: [review ipfs-pack draft proposal](https://github.com/ipfs/archives/issues/99) 
- [ ] #100: [review ipfs-s3 datastore options](https://github.com/ipfs/archives/issues/100) 
- [ ] #85: [review filestore](https://github.com/ipfs/archives/issues/85) 

### Together:
- [ ] refine the concrete use case and UX we're shooting for
- [ ] make a short list of the "big bugs" and "big optimizations" relevant for this sprint. (i can think of a couple -- file attrs, bitswap supporting paths (kills so many RTTs)  -- , but we'll want a good list to have in mind) 
- [ ] create the test workloads + scripts we'll work against:
   - for each order of magnitude of total data, from 1M -> 100TB
   - with giant files
   - with lots of little files
   - can just add tests to https://github.com/ipfs/fs-stress-test

### @flyingzumwalt:
- [x] Set up a place to track sprint stories & milestones (probably an endeavor-specific repo)
- [ ] Review the tools listed at http://climatemirror.org, consider implications, write up conclusions
- [ ] Generate List of Stories/Goals for the Sprint, associate them with a Milestone and a backlog
- [ ] prioritize the objectives (because we won't get to them all)
- [ ] plan for follow-up after the sprint is over
- [ ] Get essential stories to "Ready"

**Comment by kevina** [comment]
This sounds like it involves me.  Is there a reason I am not mentioned?

**Comment by flyingzumwalt** [comment]
@kevina this sprint arose very quickly based on sudden interest outside our org. I'm putting together the docs as quickly as I can so we can coordinate. I suspect that @jbenet and @whyrusleeping will pull you onto the sprint if you're available.

**Comment by flyingzumwalt** [comment]
## Sprint Planning: data.gov (aka 300 TB Challenge) 
Date: 2017-17-01

#### Lead: @flyingzumwalt
#### Notetaker:  @flyingzumwalt

#### Participants

- @flyingzumwalt
- @jbenet
- @whyrusleeping
- @kubuxu
- @jonnycrunch

## Notes

## Useful Links & Issues
* ipfs/archives#87: **Main Sprint Issue** for data.gov Sprint
* ipfs/archives#104: **Main data.gov Epic**: Replicate 350 TB of Data Between 3 Peers (and then the World)
* [Epics](https://github.com/ipfs/archives/issues?q=is%3Aopen+is%3Aissue+label%3Aepic+milestone%3A%22Data.gov+%28aka+300+TB+Challenge%29%22) for the whole sprint
* [ipfs-pack Stories & Epics](https://github.com/ipfs/archives/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Data.gov+%28aka+300+TB+Challenge%29%22+label%3Aipfs-pack)
* [filestore Stories & Epics](https://github.com/ipfs/archives/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Data.gov+%28aka+300+TB+Challenge%29%22+label%3Afilestore)


## Big Optimizations

**TODO**: dig up diagram @whyrusleeping created

* **Adding** is still very slow
  * adding large files is faster than adding lots of small files
  * need a way to test these things See ipfs/archives#102
  * @lgierth recently added ~3.2 TB for CCC. It took about a day to add. Performance dropped as the repo grew. Would have taken half a day if performance had stayed constant.
  * @kubuxu ran some tests (see https://github.com/ipfs/archives/issues/105#issuecomment-273235394)
  * Path forward: design good tests. See ipfs/archives#102
* **fetching from network** is very slow (won't be able to fill the pipes) 
  * tests should also address this
* **DHT with huge datasets** might get oversaturated
  * DHT is not going to scale in time for this sprint -- means we need to find a way to do the routing See ipfs/archives#120
  * {@whyrusleeping mentioned something i didn't hear..}
* **Garbage Collection** might not work with huge datasets 
  * **leaving GC out of scope for this sprint.**
* **Bitswap** hasn't really been tested yet
    * @lgierth & @whyrusleeping ran some tests on this but didn't get clear info. It took over a week to ???
    * See ipfs/archives#121
* Private Networks -- do we need it in order to do ipfs/archives#116 and ipfs/archives#120?


## Test Suite

See ipfs/archives#102

Currently not scaling well. Don't have good metrics, graphs or reports about performance -- where/when/how performance dipped under certain circumstances.

We need to know more than "Does it scale?". We need to know "how does it scale?" So we can identify the domain of problems, etc.


## Filestore

See [filestore Stories & Epics](https://github.com/ipfs/archives/issues?q=is%3Aopen+label%3Afilestore)

The current implementation mixes porcelain UX concerns with the underlying iplementation/plumbing. This makes the interfaces confusing & complicated. It also makes the underlying plumbing more complicated and less robust than it should be. 
Best approach: take the pieces of the code that we need and package it as an *experimental* feature with simple, straightforward interfaces.

@jbenet & @whyrusleeping need to sit down and figure out how they want to proceed with this. @flyingzumwalt will try to capture that info in the [filestore Stories & Epics](https://github.com/ipfs/archives/issues?q=is%3Aopen+label%3Afilestore) Main things that need to be specified:
* How to do the internals/plumbing
* What the UX should look like

## ipfs-pack

* [ipfs-pack Stories & Epics](https://github.com/ipfs/archives/issues?q=is%3Aopen+is%3Aissue+label%3Aipfs-pack)

### The case for ipfs-pack

Currently the way people use go-ipfs is with `ipfs add` which creates a duplicate copy of the added data on the machine. With `filestore` we aim to build indexes of pointers to data/blocks in-place. This solves performance concerns, but creates a brittle situation -- if you move the file, ipfs won't be able to serve it any more. ipfs-pack aims to address this by building manifest files that hold the indexes that match ipfs hashes to the content. If you store those manifest files alongside the cotnent they point to, it becomes a portable dataset.

Extending that idea, if you create little .ipfs repositories next to the manifest files, it becomes possible to

* serve that dataset as its own little ipfs node
* register the contents of that dataset with another ipfs node, serving the content directly from wherever you've stored/mounted it

#### Why implement ipfs-pack now?

* Makes the UX much smoother for providers and their peers
* packs make the a lot of these concepts clear, straightforward & relatable

**Comment by kevina** [comment]
I listened in from around 1:00 to 1:30.  

I like the idea of ipfs-pack, but I see some potential problems.  i have not had time to review the spec so it will be premature to bring them up.

I too  would like to be present for the meeting on the filestore core so I can give feedback before we try to implement anything, there are some tricky aspects regarding multiple files with the same hash that need to be addressed for this to be considered a stable format.  Most likely, the existing code can be adopted.

**Comment by flyingzumwalt** [comment]
@mejackreed so @whyrusleeping can do more realistic load testing in #126 can you please run `du -a {path-to-data}` on the datasets you've downloaded so far?

**Comment by mejackreed** [comment]
currently `2053258584      /data/master/pairtree_root/`

**Comment by Kubuxu** [comment]
@mejackreed we are also interested in whole output of this command, it will allows us to know the distribution of filesizes, directories and so on.

**Comment by mejackreed** [comment]
@Kubuxu sorry for the delay. Here you go: https://drive.google.com/file/d/0BzWuWHFTTIPERnpJSGJzYUFkYTA/view?usp=sharing

**Comment by Kubuxu** [comment]
compressed version: https://ipfs.io/ipfs/QmW82hMetgeM1K4dTFL5w9aDsZ3LYekYkeMgHfY6wtED5c

**Comment by flyingzumwalt** [comment]
Report from data.gov Sprint
====

The IPFS team have reached the end of our data.gov Sprint. Due to constraints on our very busy [Q1 Roadmap](https://waffle.io/ipfs/roadmaps), we were only able to allocate a single sprint 16-27 January 2017 (2 weeks) to work on this full-time. While we didn't reach all of the objectives, we have done our best to clear the path for our collaborators to finish the experiment. In the coming weeks, @flyingzumwalt will continue to participate in the project and the IPFS maintainers will provide information & advice when possible.

Within the IPFS team, we were excited to have the opportunity to help. This situation gets at one of the key reasons why we're building IPFS -- we want everyone to be able to hold and serve copies of the data they care about rather than relying on centralized services.


# What we Accomplished

A number of collaborators have stepped up on very short notice to replicate these datasets. We're happy to tell them that **the software is ready for you to use.** Here's what @whyrusleeping, @kubuxu, @kevina, @jbenet and @flyingzumwalt have done:

* We've written instructions for you to follow when replicating the data.gov datasets (and any other datasets). They're titled [Instructions for Replicating Large Amounts of Data with Minimal Overhead](https://github.com/ipfs/archives/tree/master/tutorials/replicating-large-datasets)
* We made version 0.4.5 of ipfs support adding content in-place. This means you can now add content to ipfs without ipfs creating a duplicate copy of the data. Using this approach cuts the storage overhead by nearly 50%. 
* We created [ipfs-pack](http://github.com/ipfs/ipfs-pack) to simplify the process of adding downloaded datasets to the ipfs network. 
* We ran some preliminary tests to confirm that everything will work. 

# Next Steps

## Next Steps with the data.gov Datasets

Specifically regarding the data.gov Datasets, next steps include:

* Finish [Downloading the datasets](https://github.com/ipfs/archives/issues/113)
* Follow the [Instructions for Replicating Large Amounts of Data with Minimal Overhead](https://github.com/ipfs/archives/tree/master/tutorials/replicating-large-datasets)
* Connect the nodes to the general IPFS Network so others can replicate the data
* Report on the Results

@flyingzumwalt will remain the main point of contact on the ipfs side coordinating this work.

## Next Steps for the IPFS Code Base

Relevant follow-up work on the IPFS code bases involve:

* ipfs-cluster: IPFS Nodes Coordinating to Hold datasets
* More Testing and Optimization
* Deduplication of Datasets

Here's a breakdown of each:

### ipfs-cluster: IPFS Nodes Coordinating to Hold datasets

The DataRescue effort has triggered multiple requests for tools that allow IPFS nodes to coordinate with each other in order to hold valuable content. We were already working on this functionality, under the name [ipfs-cluster](https://github.com/ipfs/ipfs-cluster). The captain for ipfs-cluster is @hsanjuan. That code base will be moving forward throughout the quarter.

Some relevant discussions related to ipfs-cluster:

* Discussion: [Making IPFS work for distributed archiving](https://github.com/ipfs/notes/issues/210)
* ipfs-cluster user story: [pinning rings](https://github.com/ipfs/ipfs-cluster/issues/7)
https://github.com/ipfs/notes/issues/210

### More Testing and Optimization to Come

We wish we could have done more testing and optimizing before the collaborators started replicating the actual data.gov datasets, but that work will have to wait for a few more weeks. We have two sprints scheduled later in the quarter that will be specifically focused on [Improving our Testing & CI Infrastructure](https://github.com/ipfs/pm/issues/344) and [Building a Proper Test Lab for Distributed Networks](https://github.com/ipfs/pm/issues/354). We're confident that those tests will allow us to achieve major improvements in speed, stability, configurability, and security.

### Deduplication of Datasets

In the aftermath of this high-speed effort to download datasets, people are now asking how to deduplicate datasets. This becomes especially relevant when we consider distributing and archiving datasets as they change over time -- if parts of the datasets stay the same between versions, we want to avoid storing & replicating them multiple times.

This has spurred interest in the different chunking algorithms IPFS supports. In particular, people are taking interest in rabin fingerprinting. Here are some Github issues where the discussion is happening:

* [Testing IPFS with Rabin Fingerprinting for Archival Purposes](https://github.com/ipfs/archives/issues/136)
* Issue: [Test the benefits of Rabin Fingerprinting vs normal chunking](https://github.com/ipfs/archives/issues/137)

### Anything Else?

If we've missed anything important from our list of Next Steps, please let us know so we don't lose track of it.
