### ISSUE TITLE
Epic: Register a Directory and Serve it on IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#95]
@jbenet says:
> i'd really like to get it to a point where they can comfortable say  "hey ipfs, track this dir" then "hey ipfs, serve this dir for other people"  without assumptions about where the .ipfs repo is located, disks added or removed from machines, the files moved, filestore references breaking, etc.

# Stories

- [x] #92 Register a filesystem Directory in IPFS without Duplicating Content
- [x] #98: Use ipfs-pack to Track and Directory Structure & Contents)
- [x] #108 Serve Content Directly From an IPFS Pack to IPFS Network (no intermediary node)
