### ISSUE TITLE
Story: Use ipfs-pack to Track Directory Structure & Contents

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/archives#98]
This is part of #95 _[Epic: Register a Directory and Serve it on IPFS](https://github.com/ipfs/archives/issues/95)_.

For technical details see the [draft proposal for ipfs-pack](https://github.com/ipfs/notes/issues/205)

@jbenet says
> think of `ipfs-pack` like this:   "save the output of `ipfs add --only-hash` such that we can "make absolutely damn sure" what this archive (pack) contains later, that it hashes to the exact same values, and that we move it around safely".

Excerpt from [ipfs-pack draft proposal](https://github.com/ipfs/notes/issues/205):
> **`ipfs-pack db` creates (or updates) a temporary ipfs object database**
> This command creates (or updates) a temporary ipfs object database (eg at .ipfs-pack/db). This object database contains positonal metadata for all IPLD objects contained in the pack. (It follows the ipfs repo filestore metadata concerns). It MAY be a different, simpler object-db format, or be a full-fledged ipfs node repo using filestore.

# Sub-Stories

- [x] #96 Create a pack manifest file
- [ ] #131 Create or Update a Local Pack Object Repository
- [x] #97 Validate a directory against a manifest file

**Comment by flyingzumwalt** [comment]
#131 isn't explicitly covered, but `ipfs-pack make` builds the repo for you. Considering that sufficient to close this issue.
